<?php

namespace FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoDocRepository extends EntityRepository
{
}
