<?php

namespace FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function byCompany($nomcompany) {
        $qb = $this->createQueryBuilder('c')
                ->where('c.nom = :nomsocieter')
                ->setParameter('nomsocieter', $nomcompany);
        return $qb->getQuery()->getResult();
    }
}
