<?php

namespace FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecoveryPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecoveryPasswordRepository extends EntityRepository
{

    public function AccessPasswordChange($user){

        $q = $this
            ->createQueryBuilder('r')
            ->update('FrontBundle:RecoveryPassword','r')
            ->set("r.done", true)
            ->where('r.user=:id')
            ->andWhere('r.done <> true')
            ->setParameter('id', $user)
            ->getQuery();

        $result = $q->getSingleResult();

        return $result;

    }
}
