<?php

namespace FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryRepository extends EntityRepository
{
    public function byNumSecu($numsecu) {
        $qb = $this->createQueryBuilder('s')
                ->where('s.numSecu = :numerosecurite')
                ->setParameter('numerosecurite', $numsecu);
        return $qb->getQuery()->getResult();
    }
//    public function getsalarybyId($salary) {
//        $qb = $this->createQueryBuilder('s')
//                ->where('s.numSecu = :numerosecurite')
//                ->setParameter('numerosecurite', $numsecu);
//        return $qb->getQuery()->getResult();
//    }
}
