<?php

namespace FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SignedDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignedDocRepository extends EntityRepository
{
}
