<?php

namespace BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogMuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogMuRepository extends EntityRepository
{
}
