<?php

namespace BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MassUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MassUploadRepository extends EntityRepository
{
}
