<?php

namespace BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonnalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnalisationRepository extends EntityRepository
{
}
