<?php

namespace BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZipFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipFileRepository extends EntityRepository
{
}
